In [1]:
%%bash
which python
#conda install pytorch torchvision cpuonly -c pytorch

/home/robot/miniconda3/envs/bonsai/bin/python


In [2]:
import sys
print(sys.version)
import torch
import torch.nn as nn

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from collections import OrderedDict

# Import PyTorch

from torch.autograd import Variable

from torch.autograd import Function # import Function to create custom activations
from torch.nn.parameter import Parameter # import Parameter to create custom activations with learnable parameters
from torch import optim # import optimizers for demonstrations
import torch.nn.functional as F # import torch functions
from torchvision import datasets, transforms # import transformations to use for demo

3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0]


In [17]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()

print("z, out ",z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
z, out  tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [33]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
# print(b.requires_grad)
print(b.grad_fn)
b.backward()
print (a.grad)

False
True
tensor([[ 2.4886, -1.4162],
        [30.6073, -0.5104]])


In [11]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 911.4273, -309.8727,  663.8610], grad_fn=<MulBackward0>)


In [12]:

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [13]:

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [38]:
# Code in file tensor/two_layer_net_tensor.py
import torch

device = torch.device('cpu')
# device = torch.device('cuda') # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)

# Randomly initialize weights
w1 = torch.randn(D_in, H, device=device)
w2 = torch.randn(H, D_out, device=device)

learning_rate = 1e-6
for t in range(500):
  # Forward pass: compute predicted y
  h = x.mm(w1)
  h_relu = h.clamp(min=0)
  y_pred = h_relu.mm(w2)

  # Compute and print loss; loss is a scalar, and is stored in a PyTorch Tensor
  # of shape (); we can get its value as a Python number with loss.item().
  loss = (y_pred - y).pow(2).sum()
  print(t, loss.item())

  # Backprop to compute gradients of w1 and w2 with respect to loss
  grad_y_pred = 2.0 * (y_pred - y)
  grad_w2 = h_relu.t().mm(grad_y_pred)
  grad_h_relu = grad_y_pred.mm(w2.t())
  grad_h = grad_h_relu.clone()
  grad_h[h < 0] = 0
  grad_w1 = x.t().mm(grad_h)

  # Update weights using gradient descent
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2





0 36827200.0
1 37136068.0
2 37054992.0
3 31112332.0
4 20757048.0
5 11267230.0
6 5671826.5
7 3041493.25
8 1889423.75
9 1347101.625
10 1050983.0
11 861334.9375
12 724215.75
13 617668.25
14 531586.125
15 460542.0625
16 401076.75
17 350844.8125
18 308197.46875
19 271687.0625
20 240277.96875
21 213173.984375
22 189676.0
23 169241.53125
24 151383.09375
25 135732.015625
26 121961.71875
27 109812.71875
28 99065.0
29 89532.171875
30 81055.453125
31 73503.8203125
32 66759.6484375
33 60725.0703125
34 55315.26953125
35 50456.703125
36 46088.8203125
37 42157.453125
38 38609.21875
39 35405.9375
40 32505.271484375
41 29876.99609375
42 27494.169921875
43 25327.787109375
44 23355.5703125
45 21556.97265625
46 19914.955078125
47 18414.546875
48 17042.482421875
49 15785.951171875
50 14633.884765625
51 13577.021484375
52 12607.12890625
53 11714.798828125
54 10893.4853515625
55 10137.3427734375
56 9439.8125
57 8796.6923828125
58 8203.130859375
59 7654.50244140625
60 7147.23486328125
61 6677.9580078125
62 62

In [36]:

device = torch.device('cpu')
# device = torch.device('cuda') # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)

# Randomly initialize weights
w1 = torch.randn(D_in, H, device=device)
w2 = torch.randn(H, D_out, device=device)

learning_rate = 1e-6
for t in range(500):
  # Forward pass: compute predicted y
  h = x.mm(w1)
  h_relu = h.clamp(min=0)
  y_pred = h_relu.mm(w2)

  # Compute and print loss; loss is a scalar, and is stored in a PyTorch Tensor
  # of shape (); we can get its value as a Python number with loss.item().
  loss = (y_pred - y).pow(2).sum()
  print(t, loss.item())

  # Backprop to compute gradients of w1 and w2 with respect to loss
  grad_y_pred = 2.0 * (y_pred - y)
  grad_w2 = h_relu.t().mm(grad_y_pred)
  grad_h_relu = grad_y_pred.mm(w2.t())
  grad_h = grad_h_relu.clone()
  grad_h[h < 0] = 0
  grad_w1 = x.t().mm(grad_h)

  # Update weights using gradient descent
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2

0 37477496.0
1 35445524.0
2 33695760.0
3 27748754.0
4 18673774.0
5 10567113.0
6 5553355.0
7 3036548.75
8 1847447.375
9 1261153.75
10 939651.25
11 740273.8125
12 602763.1875
13 500131.71875
14 420079.5625
15 355967.25
16 303665.78125
17 260477.984375
18 224481.859375
19 194279.65625
20 168823.078125
21 147232.765625
22 128828.375
23 113059.671875
24 99502.3125
25 87799.1015625
26 77680.6953125
27 68892.8046875
28 61235.890625
29 54541.23046875
30 48673.7578125
31 43517.79296875
32 38977.8125
33 34968.5625
34 31422.28515625
35 28278.99609375
36 25488.322265625
37 23005.283203125
38 20792.96875
39 18820.1796875
40 17056.083984375
41 15475.1572265625
42 14056.115234375
43 12781.572265625
44 11634.689453125
45 10600.8779296875
46 9667.771484375
47 8824.771484375
48 8061.95263671875
49 7371.1123046875
50 6744.4912109375
51 6175.8173828125
52 5659.02294921875
53 5189.0732421875
54 4761.1083984375
55 4371.45166015625
56 4016.202880859375
57 3691.826904296875
58 3395.05908203125
59 3123.8569335

In [39]:
# Code in file autograd/two_layer_net_autograd.py
import torch

device = torch.device('cpu')
# device = torch.device('cuda') # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold input and outputs
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)

# Create random Tensors for weights; setting requires_grad=True means that we
# want to compute gradients for these Tensors during the backward pass.
w1 = torch.randn(D_in, H, device=device, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
  # Forward pass: compute predicted y using operations on Tensors. Since w1 and
  # w2 have requires_grad=True, operations involving these Tensors will cause
  # PyTorch to build a computational graph, allowing automatic computation of
  # gradients. Since we are no longer implementing the backward pass by hand we
  # don't need to keep references to intermediate values.
  y_pred = x.mm(w1).clamp(min=0).mm(w2)
  
  # Compute and print loss. Loss is a Tensor of shape (), and loss.item()
  # is a Python number giving its value.
  loss = (y_pred - y).pow(2).sum()
  print(t, loss.item())

  # Use autograd to compute the backward pass. This call will compute the
  # gradient of loss with respect to all Tensors with requires_grad=True.
  # After this call w1.grad and w2.grad will be Tensors holding the gradient
  # of the loss with respect to w1 and w2 respectively.
  loss.backward()

  # Update weights using gradient descent. For this step we just want to mutate
  # the values of w1 and w2 in-place; we don't want to build up a computational
  # graph for the update steps, so we use the torch.no_grad() context manager
  # to prevent PyTorch from building a computational graph for the updates
  with torch.no_grad():
    w1 -= learning_rate * w1.grad
    w2 -= learning_rate * w2.grad

    # Manually zero the gradients after running the backward pass
    w1.grad.zero_()
    w2.grad.zero_()

0 38833376.0
1 34253576.0
2 32893656.0
3 28758416.0
4 21138560.0
5 12926023.0
6 7098340.0
7 3863841.25
8 2275874.5
9 1498081.25
10 1089528.25
11 848755.1875
12 689814.75
13 574813.0
14 486429.0625
15 415821.25
16 358163.625
17 310348.1875
18 270318.15625
19 236550.453125
20 207873.125
21 183347.640625
22 162260.25
23 144031.546875
24 128239.0
25 114513.109375
26 102501.78125
27 91959.0625
28 82683.375
29 74501.140625
30 67253.8984375
31 60837.265625
32 55125.77734375
33 50029.9921875
34 45475.34765625
35 41393.63671875
36 37727.81640625
37 34429.44140625
38 31457.79296875
39 28774.810546875
40 26348.48828125
41 24151.46484375
42 22159.501953125
43 20350.59765625
44 18705.97265625
45 17208.890625
46 15844.314453125
47 14599.224609375
48 13462.18359375
49 12422.3349609375
50 11470.75390625
51 10599.1513671875
52 9800.73828125
53 9068.4267578125
54 8395.6533203125
55 7777.2529296875
56 7208.388671875
57 6685.025390625
58 6202.77490234375
59 5758.19091796875
60 5348.2685546875
61 4969.6621

In [40]:
class MyReLU(torch.autograd.Function):
  """
  We can implement our own custom autograd Functions by subclassing
  torch.autograd.Function and implementing the forward and backward passes
  which operate on Tensors.
  """
  @staticmethod
  def forward(ctx, x):
    """
    In the forward pass we receive a context object and a Tensor containing the
    input; we must return a Tensor containing the output, and we can use the
    context object to cache objects for use in the backward pass.
    """
    ctx.save_for_backward(x)
    return x.clamp(min=0)

  @staticmethod
  def backward(ctx, grad_output):
    """
    In the backward pass we receive the context object and a Tensor containing
    the gradient of the loss with respect to the output produced during the
    forward pass. We can retrieve cached data from the context object, and must
    compute and return the gradient of the loss with respect to the input to the
    forward function.
    """
    x, = ctx.saved_tensors
    grad_x = grad_output.clone()
    grad_x[x < 0] = 0
    return grad_x


device = torch.device('cpu')
# device = torch.device('cuda') # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold input and output
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)

# Create random Tensors for weights.
w1 = torch.randn(D_in, H, device=device, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
  # Forward pass: compute predicted y using operations on Tensors; we call our
  # custom ReLU implementation using the MyReLU.apply function
  y_pred = MyReLU.apply(x.mm(w1)).mm(w2)
 
  # Compute and print loss
  loss = (y_pred - y).pow(2).sum()
  print(t, loss.item())

  # Use autograd to compute the backward pass.
  loss.backward()

  with torch.no_grad():
    # Update weights using gradient descent
    w1 -= learning_rate * w1.grad
    w2 -= learning_rate * w2.grad

    # Manually zero the gradients after running the backward pass
    w1.grad.zero_()
    w2.grad.zero_()

0 36505708.0
1 31370954.0
2 28555918.0
3 24125838.0
4 17863156.0
5 11631517.0
6 6983042.5
7 4144855.0
8 2575129.75
9 1726715.5
10 1250911.125
11 963414.0
12 774563.25
13 640416.125
14 539107.625
15 459325.34375
16 394710.25
17 341417.71875
18 296780.84375
19 259102.875
20 226987.4375
21 199551.796875
22 175993.3125
23 155701.578125
24 138124.6875
25 122852.1015625
26 109551.5078125
27 97943.375
28 87756.453125
29 78801.4765625
30 70903.5859375
31 63924.953125
32 57736.16015625
33 52235.73046875
34 47335.1015625
35 42964.375
36 39056.69921875
37 35553.765625
38 32405.841796875
39 29573.81640625
40 27021.083984375
41 24714.958984375
42 22630.25390625
43 20743.33203125
44 19037.8203125
45 17489.85546875
46 16082.564453125
47 14801.1640625
48 13633.60546875
49 12568.6005859375
50 11596.03515625
51 10706.818359375
52 9893.0009765625
53 9147.2119140625
54 8463.109375
55 7835.59521484375
56 7258.92822265625
57 6728.8095703125
58 6240.77685546875
59 5791.54345703125
60 5377.60546875
61 4995.78

In [41]:
import torch

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs.
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Use the nn package to define our model and loss function.
model = torch.nn.Sequential(
          torch.nn.Linear(D_in, H),
          torch.nn.ReLU(),
          torch.nn.Linear(H, D_out),
        )
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use Adam; the optim package contains many other
# optimization algorithms. The first argument to the Adam constructor tells the
# optimizer which Tensors it should update.
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
for t in range(500):
  # Forward pass: compute predicted y by passing x to the model.
  y_pred = model(x)

  # Compute and print loss.
  loss = loss_fn(y_pred, y)
  print(t, loss.item())
  
  # Before the backward pass, use the optimizer object to zero all of the
  # gradients for the Tensors it will update (which are the learnable weights
  # of the model)
  optimizer.zero_grad()

  # Backward pass: compute gradient of the loss with respect to model parameters
  loss.backward()

  # Calling the step function on an Optimizer makes an update to its parameters
  optimizer.step()

0 733.4744873046875
1 715.1434326171875
2 697.4378662109375
3 680.3403930664062
4 663.6915893554688
5 647.5369262695312
6 631.9785766601562
7 616.8239135742188
8 602.136962890625
9 587.8182373046875
10 573.8710327148438
11 560.3023071289062
12 547.04736328125
13 534.1736450195312
14 521.658447265625
15 509.6225280761719
16 497.893798828125
17 486.5040588378906
18 475.412841796875
19 464.67926025390625
20 454.2256164550781
21 444.0511474609375
22 434.153564453125
23 424.4690246582031
24 415.0345458984375
25 405.8457336425781
26 396.9121398925781
27 388.23455810546875
28 379.81622314453125
29 371.57794189453125
30 363.5458068847656
31 355.7034912109375
32 348.005859375
33 340.435791015625
34 333.0218811035156
35 325.7752380371094
36 318.6944580078125
37 311.741943359375
38 304.9066467285156
39 298.2055969238281
40 291.67181396484375
41 285.2890319824219
42 279.02197265625
43 272.87542724609375
44 266.8500061035156
45 260.928466796875
46 255.14207458496094
47 249.4636688232422
48 243.8845